### PR TITLE
update farm filter

### PR DESCRIPTION
**Pull request by mariobassem**
add more fields to farm filter

### Description

This PR adds NodeStatus, NodeRentedBy, NodeAvailableFor, NodeHasGPU, NodeCertified fields for farm filter

### Related Issues

- #263

### CODE REVIEW

**Comment by Omarabdul3ziz** [comment]
Good work from a good developer ya Mario :D

Just a couple of small comments:
- Can we update the swagger docs with the new farm filters?

- The `serializeFilters` function helps reduce code duplication, but it's only applied to farm/node filters. can we apply it to twin, contract, and stats filters too?


- I am not sure if the certification for the farm and nodes on it should be the same. but shouldn't `NodeCertified` filter check on the certification on the node table not in farm?
  https://github.com/threefoldtech/tfgrid-sdk-go/blob/4965ea56411dd7b02a7219c63f64a51278f00daf/grid-proxy/internal/explorer/db/postgres.go#L623-L625
  tried to filter the certified node with `/nodes?certification_type=certified` and i got 3 node in farm 1 so `/farms?node_certified=true` should list it but it returns empty list. farm 1 itself has `"certificationType": "NotCertified"`


- In `/nodes?available_for=89` filter the list is ordered to return the rented nodes at the begging can we do that with `/farms?node_available_for=89` too
  https://github.com/threefoldtech/tfgrid-sdk-go/blob/4965ea56411dd7b02a7219c63f64a51278f00daf/grid-proxy/internal/explorer/db/postgres.go#L561-L563


- Things look good but i got these error on logs each time `/farms` endpoint is requested

**Comment by mariobassem** [comment]
fixed above comments except for the `SerializeFilter` part, it's done in another PR #244. I only added it here because I needed it while running farm tests.

**Review by Omarabdul3ziz — APPROVED** [review]
LGTM

**Review by alichaddad — APPROVED** [review]

**Comment by mariobassem** [comment]
had a small discussion with @alichaddad about the farms query. he had a concern about what would happen if a node had multiple gpus. we reached a conclusion that whatever the node data that resulted, the query result would be grouped by farm information in the end, and all node information would be discarded.

**Pull request merged**
